name: Build and Deploy WebGL

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles(**/Assets/**, **/Packages/**, **/ProjectSettings/**) }}
          restore-keys: |
            Library-

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Unity - Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2022.3.48f1
          targetPlatform: WebGL
          allowDirtyBuild: true
          buildName: redalert
          buildPath: build
          versioning: None

      - name: Upload WebGL artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGL
          path: build/WebGL

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download WebGL artifact
        uses: actions/download-artifact@v4
        with:
          name: WebGL
          path: webgl

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webgl

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
